[package]
name = "teloren"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.11.0"
termion = "1.5"
clap = "2.33"
specs = { git = "https://github.com/amethyst/specs.git", rev = "7a2e348ab2223818bad487695c66c43db88050a5" }
veloren-client = { git = "https://gitlab.com/veloren/veloren.git", branch = "master" }
veloren-common = { git = "https://gitlab.com/veloren/veloren.git", branch = "master", features = ["no-assets"] }
crossbeam = "=0.7.2"
tracing = "0.1" 

[profile.dev]
opt-level = 2
overflow-checks = false